Added authentication note to ClickPipes FAQ
ClickHouse/clickhouse-docs pull request #1348
Opened 2023-07-13 14:40 UTC by Ryado

2023-07-13 14:51 UTC, DanRoscigno requested changes

2023-07-13 14:51 UTC, DanRoscigno commented on docs/en/integrations/data-ingestion/clickpipes/index.md
> +- **What authentication mechanism ClickPipes for Kafka Supports ?**
```suggestion
- **What authentication mechanisms are supported for ClickPipes for Kafka?**
```

2023-07-13 14:51 UTC, DanRoscigno commented on docs/en/integrations/data-ingestion/clickpipes/index.md
> +  ClickPipes for Kafka support [SASL/PLAIN](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_plain.html) authentication with TLS encryption.
```suggestion
  ClickPipes for Kafka supports [SASL/PLAIN](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_plain.html) authentication with TLS encryption.
```

2023-07-19 21:05 UTC, mshustov approved these changes

2023-07-20 16:05 UTC, merged