Updated scaling.md for revised scaling docs
ClickHouse/clickhouse-docs pull request #1516
Opened 2023-09-12 19:09 UTC by aashishkohli

Updated autoscaling docs

2023-09-12 19:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=1516) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=1516) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-docs?pullRequest=1516) it.</sub>

2023-09-13 01:17 UTC, justindeguzman approved these changes

2023-09-15 21:43 UTC, tbragin commented
Although I was not listed as a reivewer, I took a look and it appears to be an improvement. Thank you for working on this @aashishkohli !

2023-09-15 23:08 UTC, melvynator requested changes

2023-09-15 23:08 UTC, melvynator commented on docs/en/cloud/manage/scaling.md
> +SELECT hostname(), getSetting('max_threads'), formatReadableSize(getSetting('max_memory_usage'))
Should be replace by:

```
SELECT *
FROM clusterAllReplicas('default', view(
    SELECT
        hostname() AS server,
        getSetting('max_threads') as cpu_cores,
         formatReadableSize(getSetting('max_memory_usage')) as memory
    FROM system.one
))
ORDER BY server ASC
SETTINGS skip_unavailable_shards = 1
```

2023-09-18 03:10 UTC, justindeguzman commented on docs/en/cloud/manage/scaling.md
> +SELECT hostname(), getSetting('max_threads'), formatReadableSize(getSetting('max_memory_usage'))
Thanks! I'll update this

2023-09-18 03:13 UTC, merged