[DOCUMENTATION UPDATE] Streamkap partner integration, category Data Ingestion
ClickHouse/clickhouse-docs pull request #2065
Opened 2024-02-19 15:54 UTC by b0dea

2024-02-19 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2065) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2065) before we can accept your contribution.<br/><hr/>**Alexandru Bodea** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-docs?pullRequest=2065) it.</sub>

2024-02-19 15:57 UTC, streamkap approved these changes

2024-02-20 19:00 UTC, johnnymatthews requested changes

2024-02-20 19:00 UTC, johnnymatthews commented on docs/en/integrations/index.mdx
> +|Streamkap|<img src={require('./images/logos/streamkap-logo.png').default} class="image" alt="Streamkap logo" style={{width: '3rem', 'background-color': 'transparent'}}/>|Data ingestion|Setup real-ti
Should probably define what _CDC_ means in this context. Can you add the string that `CDC` represents?

2024-02-21 16:19 UTC, mshustov approved these changes

2024-02-28 17:49 UTC, johnnymatthews requested changes
I can't directly edit this PR, nor make suggestions for some reason... 

@b0dea please move line 172 to 166 so that the list remains in alphabetical order.

2024-02-29 22:57 UTC, johnnymatthews approved these changes
Perfect, thanks for that change!

2024-02-29 23:00 UTC, merged