Adding Redpanda Cloud as a 3rd party cloud based Kafka connection
ClickHouse/clickhouse-docs pull request #2116
Opened 2024-03-07 14:38 UTC by dunithd

Added Redpanda Cloud, a 3rd party Kafka API-compatible cloud platform, as a potential upstream for ClickHouse.

2024-03-07 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-docs?pullRequest=2116) it.</sub>

2024-03-07 15:27 UTC, pjhampton approved these changes
Thank you!

2024-03-07 15:27 UTC, pjhampton requested changes
Please sign the CLA

2024-03-14 16:14 UTC, dunithd commented
Signed the CLA just now. Sorry about the delay.

2024-03-14 18:13 UTC, pjhampton approved these changes

2024-03-14 18:13 UTC, merged