Add Quesma to list of the partners
ClickHouse/clickhouse-docs pull request #2410
Opened 2024-06-17 15:27 UTC by jakozaur

Elastic / OpenSearch static is popular in observability (e.g. trip.com uses Kibana). With Quesma, it is possible to use it natively with Clickhouse. Added link.

2024-06-17 15:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2410) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2410) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-docs?pullRequest=2410) it.</sub>

2024-06-18 11:30 UTC, pjhampton requested changes
https://quesma.com/quesma-for-elk has no mention of ClickHouse. The only references I could see to ClickHouse are in an image on the home page and the downloadable PDF referenced as `Elastic / OpenSearch Stacks Interoperability`.

I would be beneficial to get some more ClickHouse specific detail on this integration.

2024-06-18 15:24 UTC, jakozaur commented
@pjhampton, we updated the website as you suggested. Please check again.

We also had a previous conversation with @Ryado from ClickHouse about Quesma.

2024-06-18 16:24 UTC, pjhampton commented on docs/en/integrations/index.mdx
> +|Quesma|<QuesmaSVG style={{width: '3rem'}} />|Data integration|Use Elasticsearch / OpenSearch stack and API. E.g. Kibana and OpenSearch Dashboards with data in ClickHouse.|[Website](https://quesma.co
How about:

```suggestion
|Quesma|<QuesmaSVG style={{width: '3rem'}} />|Data integration|Use Kibana and OpenSearch Dashboards with data in ClickHouse.|[Website](https://quesma.com/quesma-for-elk)|
```

2024-06-18 18:41 UTC, jakozaur commented
@pjhampton applied fixes and styled our logo for the `light` and `dark` theme.
![Screenshot 2024-06-18 at 20 36 10](https://github.com/ClickHouse/clickhouse-docs/assets/972989/2399895a-5098-46eb-8ec1-7219e0206693)
![Screenshot 2024-06-18 at 20 36 04](https://github.com/ClickHouse/clickhouse-docs/assets/972989/8c9c1f85-bcad-4346-b1f8-4eabdbd34adf)

2024-06-18 19:13 UTC, pjhampton approved these changes
Rock on! Look forward to seeing more from Quesma in the future!

2024-06-18 19:13 UTC, merged