Astrato Analytics Integration and Data Integration
ClickHouse/clickhouse-docs pull request #2719
Opened 2024-10-21 15:21 UTC by piersbatch

Added listings in partner & data viz section for Astrato Analytics, along with required images.

## Summary

## Checklist
- [ ] Delete items not relevant to your PR
- [ ] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
- [ ] If adding a new integration page, also add an entry to the integrations list here: https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/index.mdx

2024-10-21 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-docs?pullRequest=2719) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-docs?pullRequest=2719) it.</sub>

2024-11-06 10:12 UTC, laeg commented
@piersbatch was this tested locally?

Getting the following error when trying to render the PR:

```
Compiled with problems:X

ERROR in ./docs/en/integrations/data-visualization/astrato-and-clickhouse.md

Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
SyntaxError: /Users/laeg/ClickHouse/clickhouse-docs/docs/en/integrations/data-visualization/astrato-and-clickhouse.md: Unexpected token, expected "," (32:127)

  30 | ​`}</li>
  31 | <li parentName="ul">{`Click on the `}<strong parentName="li">{`New Data Connection`}</strong>{` button in the top right side of the screen.`}
> 32 | <img  src={require('./images/astrato_1_dataconnection.png').default}  class="image"  alt="Astrato Data Connection"  style={{max-width:'50%',  'background-color':  'transparent'}}/>
     |                                                                                                                                ^
  33 | </li>
  34 | </ul>
  35 | <br/>
```

2024-11-06 10:20 UTC, laeg requested changes
images refs and css styles need to be updated. 

Can you test these docs locally and upload a screenshot please when completed. Thanks

2024-11-06 10:20 UTC, laeg commented on docs/en/integrations/data-visualization/astrato-and-clickhouse.md
> +<img  src={require('./images/astrato_2a_clickhouse_connection.png').default}  class="image"  alt="Astrato ClickHouse Data Connection"  style={{max-width:'50%',  'background-color':  'transparent'}}/>
Need to be changed to `width`

2024-11-06 10:20 UTC, laeg commented on docs/en/integrations/data-visualization/astrato-and-clickhouse.md
> +<img  src={require('./images/astrato_1_dataconnection.png').default}  class="image"  alt="Astrato Data Connection"  style={{max-width:'50%',  'background-color':  'transparent'}}/>
needs to be changed to `width`

2024-11-06 10:20 UTC, laeg commented on docs/en/integrations/data-visualization/astrato-and-clickhouse.md
> +<img  src={require('./images/astrato_4b_clickhouse_data_view.png').default}  class="image"  alt="Astrato connect to ClickHouse User Access"  style={{width:'50%',  'background-color':  'transparent'}}
file does not exist. 

should be: `docs/en/integrations/data-visualization/images/astrato_4b_clickhouse_data_view_joins.png`

2024-11-06 10:20 UTC, laeg commented on docs/en/integrations/data-visualization/astrato-and-clickhouse.md
> +<img  src={require('./images/astrato_4c_clickhouse_data_view.png').default}  class="image"  alt="Astrato connect to ClickHouse User Access"  style={{width:'50%',  'background-color':  'transparent'}}
file does not exist.

should be: `docs/en/integrations/data-visualization/images/astrato_4c_clickhouse_completed_data_view.png`

2024-11-13 21:49 UTC, piersbatch commented
@laeg I'm back from annual leave and have done the changes, which have been tested locally.

2024-11-20 16:45 UTC, laeg commented
cheers @piersbatch. can you rebase this branch(checks are saying there are conflicts) and also add yourselves to the table in [`data-visualisation.md`](https://github.com/ClickHouse/clickhouse-docs/pull/2719/files#diff-0fd8edb756195c56627c5e21083908d8fee12ae873906ee33d63ba42fcaede8eR44)

2024-11-21 08:56 UTC, closed without merging