Clickable breadcrumbs
ClickHouse/clickhouse-docs pull request #2779
Opened 2024-11-12 21:13 UTC by Blargian

Closes #2636. Introduces changes to clean up the navigation of docs together with [](). 

**NB - we will need to try merge this PR and the other at the same time**

## Changes

In many places we show an overview page as a sub-child of the category, such as here:

![image](https://github.com/user-attachments/assets/4a8d0c58-43e9-4fe1-ad79-bdafe4210f7c)

In my opinion this clutters the sidebar, especially when the overview page has the same name as the category. This PR makes a small change to the `sidebarItemsGenerator` such that any file ending `index.md` will not show as a sub-child of the category. The category itself is then given the link to the overview or index page and becomes clickable:

![image](https://github.com/user-attachments/assets/c2c0363b-595f-4e93-ba0e-8fac8a5a1094)

Further more, breadcrumbs often did not link to anywhere such as here, because 'introduction' was a category and not a specific page:

![image](https://github.com/user-attachments/assets/bbc8ab41-8b3e-49b2-b181-ea33772015bb)

Index files are added (in a separate PR) in some places and categories in the sidebar linked such that breadcrumbs are clickable:

![Screencast from 12-11-2024 22_08_06](https://github.com/user-attachments/assets/308d0178-a5ae-42ac-883d-e7b57f3ab232)

## Checklist
- [X] Delete items not relevant to your PR
- [ ] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
- [X] If adding a new integration page, also add an entry to the integrations list here: https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/index.mdx

2024-11-12 21:32 UTC, Blargian commented
DocsCheck fails:

```
Error:  Loading of version failed for version current
Error:  Unable to build website for locale en.
Error:  Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- en/engines/index
- en/sql-reference/functions/functions-index
```
This is because the former is added in [#71846](https://github.com/ClickHouse/ClickHouse/pull/71846) over at main repo and the latter because `en/sql-reference/functions/functions-index` was previously `en/sql-reference/functions/index`. Rename happens in that PR as well.

May also need to add a redirect for that.

2024-12-16 22:22 UTC, Blargian commented on docs/en/sql-reference/functions/functions-index.md
> +---
Changes in this file were actually made in [71846](https://github.com/ClickHouse/ClickHouse/pull/71846) on main repo but I am committing it here as this PR fails without it. Same for `engines/index.md`

2025-01-06 16:28 UTC, Blargian commented
Note to self: add back table of contents import to system-tables/index.md

2025-01-06 16:37 UTC, gingerwizard commented on src/components/TableOfContents/index.ts
> +export { TableOfContents } from "./table_of_contents";
nit: newline

2025-01-06 16:37 UTC, gingerwizard commented on docs/en/chdb/guides/table_of_contents.json
> +]
nit: newline

2025-01-13 09:59 UTC, gingerwizard commented on docs/en/cloud/changelogs/autogenerate_table_of_contents.py
> +    main()
nit: new lines

2025-01-13 10:00 UTC, gingerwizard commented on docs/en/cloud/changelogs/autogenerate_table_of_contents.py
> +import json
refactor into above. Move scripts to src/

2025-01-13 10:02 UTC, gingerwizard commented on docs/en/cloud/manage/api/api-reference-index.md
> +---
shouldnt be checked in

2025-01-13 10:03 UTC, gingerwizard commented on docs/en/cloud/manage/api/keys-api-reference.md
> +
remove

2025-01-13 10:04 UTC, gingerwizard commented on docs/en/cloud/manage/billing.md
> +slug: /en/cloud/manage/billing/overview
redirect

2025-01-13 10:05 UTC, gingerwizard commented on docs/en/cloud/manage/billing/marketplace/index.md
> +slug: /en/cloud/manage/marketplace/
redirect

2025-01-13 10:06 UTC, gingerwizard commented on docs/en/cloud/reference/index.md
> +| [Changelogs](/en/cloud/reference/changelogs)                                | Cloud ChangeLogs and Release Notes.                                                                       |
nit can we align

2025-01-13 10:11 UTC, gingerwizard requested changes
we need these redirects - linked in nuture and website

2025-01-14 09:50 UTC, gingerwizard commented on docs/en/cloud/security/private-link-overview.md
> -# Private Link Overview
revert this its an AWS feature name

2025-01-14 09:52 UTC, gingerwizard commented on docs/en/data-modeling/data-modeling-overview.md
> +---
should this be index.md

2025-01-14 09:56 UTC, gingerwizard commented on docs/en/integrations/migration/overview.md
> +keywords: [clickhouse, migrate, migration, migrating, data]
slug?

2025-01-14 09:59 UTC, gingerwizard requested changes
minor changes

2025-01-15 10:05 UTC, gingerwizard approved these changes

2025-01-15 10:07 UTC, gingerwizard commented
This is good to merge. Some minor stuff:

- top menus should now link to headers where possibel
- Fix /docs/en/cloud/bestpractices
- add descriptions to pages so all tables are consistent
- remove `docs/en/optimize`

2025-01-15 10:07 UTC, merged