Adds new knowledgebase article on ClickPipes privatelink.
ClickHouse/clickhouse-docs pull request #2837
Opened 2024-11-27 20:14 UTC by natalyjazzviolin

## Summary
Adds new knowledgebase article on ClickPipes privatelink.

2024-11-27 20:15 UTC, iskakaushik approved these changes

2024-11-27 22:32 UTC, iskakaushik commented
@natalyjazzviolin  -- I think we should leave the yarn.lock around

2024-11-27 22:32 UTC, iskakaushik requested changes
revert yarn.lock

2024-12-06 12:11 UTC, gingerwizard approved these changes
LGTM now

2024-12-06 12:11 UTC, merged