[java-client] doc updates for configuration
ClickHouse/clickhouse-docs pull request #2942
Opened 2024-12-20 19:36 UTC by chernser

## Summary
- configuration documentation update
- deprecation warning for client-v1

Closes https://github.com/ClickHouse/clickhouse-java/issues/1884
Closes https://github.com/ClickHouse/clickhouse-java/issues/1950
Closes  

## Checklist
- [ ] Delete items not relevant to your PR
- [ ] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
- [ ] If adding a new integration page, also add an entry to the integrations list here: https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/index.mdx

2024-12-27 09:34 UTC, gingerwizard commented on docs/en/integrations/language-clients/java/client-v1.md
> +This library will be depreceted on `February, 28, 2025`. It means no releases after and support.
spelling `depreceted` -> `deprecated`. `It means no releases after and support. ` -> `This means no further releases and support issues will not be addressed. `

2024-12-27 09:34 UTC, gingerwizard commented on docs/en/integrations/language-clients/java/client-v2.md
> +| setClientNetworkBufferSize(int size) | - `size` - size in bytes | Sets size of a buffer in application memory space that is used to copy data back-and-forth between socket and application. Greater
missing full stop

2024-12-27 09:35 UTC, gingerwizard commented on docs/en/integrations/language-clients/java/client-v2.md
> +  <dd>Sets individual server settings for an operation.</dd>
Nit: can we be consistent. Ether we terminate with a full stop or we don't.

2024-12-27 09:35 UTC, gingerwizard commented on docs/en/integrations/language-clients/java/client-v2.md
> +  <dd>Sets a configuration option in raw format. This is not a server settings.</dd>
`settings` -> `setting`

2024-12-27 09:35 UTC, gingerwizard commented on docs/en/integrations/language-clients/java/client-v2.md
> +  <dd>Sets a configuration option in raw format. This is not a server settings.</dd>
`settings` -> `setting`

2024-12-27 09:36 UTC, gingerwizard requested changes
Spelling issues but id like @mshustov to provide final approvals

2024-12-27 18:39 UTC, chernser commented
@gingerwizard thank you for the review! Will update.

2024-12-28 09:41 UTC, mshustov approved these changes

2024-12-28 09:48 UTC, merged