minor clean up of repo
ClickHouse/clickhouse-docs pull request #2950
Opened 2024-12-24 07:38 UTC by Blargian

## Summary
Minor repo cleanup:

- add a `contributing` folder to house anything contribution related. Move `CODE_OF_CONDUCT.md` to this folder.
- add `templates_and_guides` directory to above mentioned folder to house any templates or guides, added a readme to explain the purpose.
- move scripts in root to `/scripts`
- move the image in the root to `/images`
- delete `pagerank.csv` ?

## Checklist
- [ ] Delete items not relevant to your PR
- [ ] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
- [ ] If adding a new integration page, also add an entry to the integrations list here: https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/index.mdx

2024-12-27 09:30 UTC, gingerwizard commented
@Blargian the change log generation script is causing the build to fail.

```
[copyClickHouseRepoDocs.sh] Copying completed successfully
[copyClickHouseRepoDocs.sh] Generate changelog
scripts/copyClickHouseRepoDocs.sh: line 36: ClickHouse/CHANGELOG.md: No such file or directory
[copyClickHouseRepoDocs.sh] An error occurred: Generating changelog
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn new-build" exited with 1
```

2024-12-27 09:31 UTC, gingerwizard requested changes
see build log

2024-12-30 16:27 UTC, gingerwizard commented
@Blargian 
```
Module not found: Error: Can't resolve '@site/docs/en/_snippets/_system_table_cloud.md' in '/vercel/path0/docs/en/operations/system-tables'
Module not found: Error: Can't resolve '@site/docs/en/_snippets/_system_table_cloud.md' in '/vercel/path0/docs/en/operations/system-tables'
```

2024-12-30 17:25 UTC, Blargian commented
> @site/docs/en/_snippets/_system_table_cloud.md

Builds and runs okay locally. I'll need to check how things are set up on vercel, look at the logs there etc. I don't currently have any vercel deployment preview access. Will take a look next week.

2025-01-21 16:58 UTC, closed without merging