Update adopters.md
ClickHouse/clickhouse-docs pull request #484
Opened 2022-10-24 15:15 UTC by alexey-milovidov

2022-10-25 14:55 UTC, DanRoscigno requested changes

2022-10-25 14:55 UTC, DanRoscigno commented on docs/en/about-us/adopters.md
> +| <a href="https://opstrace.com/" class="favicon">Opstrace</a> | Observability | — | — | — | [Tweet, 2022](https://mobile.twitter.com/avik6028/status/1584547816235741185) |
```suggestion
| <a href="https://opsverse.io/" class="favicon">OpsVerse</a> | Observability | — | — | — | [Tweet, 2022](https://twitter.com/OpsVerse/status/1584548242100219904) |  
```

2022-10-26 04:00 UTC, alexey-milovidov commented
It was Opstrace when I added it :) The company was acquired by GitLab. But I found some places when it was mentioned as a dedicated use case and decided to add it just in case.

If Opsverse also using ClickHouse let's add them both :)

2022-10-26 15:50 UTC, DanRoscigno commented
> It was Opstrace when I added it :) The company was acquired by GitLab. But I found some places where it was mentioned as a dedicated use case and decided to add it just in case.
> 
> If Opsverse also using ClickHouse let's add them both :)

I found a good reference for Opstrace: https://gitlab.com/gitlab-org/opstrace/jaeger-clickhouse/-/blob/main/README.md I will add both.

2022-10-26 20:34 UTC, DanRoscigno approved these changes

2022-10-26 20:35 UTC, merged