Fixed main page CSS
ClickHouse/clickhouse-docs pull request #65
Opened 2022-04-29 20:23 UTC by peledni

Related to: https://github.com/ClickHouse/product/issues/40

2022-05-02 08:52 UTC, gingerwizard requested changes

2022-05-02 08:52 UTC, gingerwizard commented on src/css/custom.css
> +}
insert empty line

2022-05-04 15:36 UTC, rfraposa approved these changes
I don't know what it does, but curious to see if it works. Thanks for your help!

2022-05-04 21:09 UTC, merged

2022-05-04 21:19 UTC, rfraposa commented
The home page looks good, but the footer is getting pushed down beyond the bottom on all the other pages. I will leave it merged for now...and see if that's an issue with anyone

2022-05-04 22:02 UTC, peledni commented
@rfraposa I did that on purpose, pages without a lot of content looked a bit bad (and I checked other sites using docsaurus and they do the same). If you want to revert it it's just removing 1 line of css.

2022-05-04 22:25 UTC, rfraposa commented
@peledni  - it's growing on me! Let's leave it 😄