Restructure kafka docs
ClickHouse/clickhouse-docs pull request #740
Opened 2023-02-03 13:02 UTC by mshustov

The PR revamped the structure of Kafka docs to make it more use-case centric.
The docs are split into categories depending on the deployment type of Kafka. 
The high-level structure:
```
- Introduction
- Choosing an Approach
- Kafka Table Engine
- Kafka Connect
- Self-managed Kafka
  - ClickHouse Kafka Connect Sink
  - Kafka Connect JDBC Connector
  - Vector with Kafka
- Confluent Platform
  - HTTP Sink Connector
- Amazon MSK
  - ClickHouse Kafka Connect Sink on Amazon MSK
- Kafka Samples
```
`Kafka Table Engine` is on the top level since it can be used with any Kafka deployment.
`Kafka Connect` is a small intro Kafka Connect framework that can be used in different deployment types.

2023-02-06 10:23 UTC, Ryado requested changes
we should have a clear navigation in the menu that reflects the decision tree:

* Kafka Table Engine 
* Cloud-based Kafka Connectivity 
   * Confluent Platform
   * Amazon MSK
* Self managed Kafka Connectivity
   * ClickHouse Kafka Connect Sink
   * Kafka Connect JDBC Connector
   * Vector with Kafka

it means we need to also update `docs/en/integrations/kafka/kafka-choosing-an-approach` to display the decision process

2023-02-06 10:23 UTC, Ryado commented on docs/en/integrations/data-ingestion/kafka/kafka-connect-intro.md
> +For users that prefer to manage the Kafka ClickHouse interaction external to ClickHouse, Kafka Connect provides an alternative. As of the time of writing, there are several approaches to using Kafka
This page is redundant IMO

2023-02-07 11:12 UTC, Ryado approved these changes

2023-02-07 11:38 UTC, DanRoscigno commented
@mshustov do you want to wait for any more reviews, or should I merge this now?

2023-02-07 11:51 UTC, merged